services:
  backend:
    image: bynote-backend
    build: ./backend
    pull_policy: never
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    volumes:
      - ./backend:/app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
  frontend:
    image: bynote-frontend
    pull_policy: never
    build: ./frontend
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env
    # develop:
    # watch:
    #   - path: ./frontend/app
    #     action: sync
    #     target: /app/app
    #   - path: ./frontend/package.json
    #     action: rebuild
    command: ["npm", "run", "dev", "--", "--port", "5173", "--host", "0.0.0.0"]
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg14
    container_name: bynote-postgres
    env_file:
      - ./database/.env
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data:
  frontend_node_modules:
