services:
  backend:
    image: bynote-backend
    build: ./backend
    ports:
      - 8080:8000
    develop:
      watch:
        - path: ./backend/app
          action: sync
          target: /app/app
        - path: ./backend/requirements.txt
          action: rebuild
