"""empty message

Revision ID: 168d81589bb4
Revises: 1941f2db2056
Create Date: 2025-07-16 17:58:15.771074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168d81589bb4'
down_revision: Union[str, None] = '1941f2db2056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_workspace_slug_per_user', 'workspaces', ['user_id', '_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_slug_per_user', 'workspaces', type_='unique')
    # ### end Alembic commands ###
