"""empty message

Revision ID: 1941f2db2056
Revises: 4206fa223367
Create Date: 2025-07-14 01:27:15.268744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1941f2db2056'
down_revision: Union[str, None] = '4206fa223367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('_slug', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', '_slug')
    # ### end Alembic commands ###
