"""Change on embedding referencing

Revision ID: 2a90d7cec6a1
Revises: 735e5b7ba826
Create Date: 2025-04-16 17:11:11.653092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a90d7cec6a1'
down_revision: Union[str, None] = '735e5b7ba826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('entity_field', sa.String(length=50), nullable=False))
    op.drop_constraint('notes_embedding_id_fkey', 'notes', type_='foreignkey')
    op.drop_column('notes', 'embedding_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('embedding_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('notes_embedding_id_fkey', 'notes', 'embeddings', ['embedding_id'], ['id'])
    op.drop_column('embeddings', 'entity_field')
    # ### end Alembic commands ###
