"""Adding of default workspace id in Users table

Revision ID: 37243e144a89
Revises: e70aff5b57e1
Create Date: 2025-05-17 18:56:59.830968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37243e144a89'
down_revision: Union[str, None] = 'e70aff5b57e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_workspace_id', sa.Uuid(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_workspace_id')
    # ### end Alembic commands ###
