"""Slugs

Revision ID: 47087468c90b
Revises: c9c86eb65e88
Create Date: 2025-04-14 02:37:41.575753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47087468c90b'
down_revision: Union[str, None] = 'c9c86eb65e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('_slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'notes', ['_slug'])
    op.add_column('projects', sa.Column('_slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'projects', ['_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='unique')
    op.drop_column('projects', '_slug')
    op.drop_constraint(None, 'notes', type_='unique')
    op.drop_column('notes', '_slug')
    # ### end Alembic commands ###
