"""embedding_id to notes

Revision ID: 735e5b7ba826
Revises: 3afcdb043b3b
Create Date: 2025-04-16 02:04:13.473827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735e5b7ba826'
down_revision: Union[str, None] = '3afcdb043b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('embedding_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'notes', 'embeddings', ['embedding_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'embedding_id')
    # ### end Alembic commands ###
