"""Creation of workspace

Revision ID: ac9193135831
Revises: 20584afcff3f
Create Date: 2025-05-17 18:18:17.726401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9193135831'
down_revision: Union[str, None] = '20584afcff3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('url_name', sa.String(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('ui_color', sa.String(), nullable=True),
    sa.Column('ui_icon', sa.String(), nullable=True),
    sa.Column('ui_theme', sa.String(), nullable=True),
    sa.Column('ui_font', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_name')
    )
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('workspace_id', sa.Uuid(), nullable=False))
    op.drop_constraint('uq_user_project_slug', 'projects', type_='unique')
    op.create_unique_constraint('uq_workspace_project_slug', 'projects', ['workspace_id', '_slug'])
    op.drop_constraint('projects_user_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['id'])
    op.drop_column('projects', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_user_id_fkey', 'projects', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_workspace_project_slug', 'projects', type_='unique')
    op.create_unique_constraint('uq_user_project_slug', 'projects', ['user_id', '_slug'])
    op.drop_column('projects', 'workspace_id')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'is_deleted')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
