"""Remove url_name from Workspace, will use id

Revision ID: e70aff5b57e1
Revises: ac9193135831
Create Date: 2025-05-17 18:50:13.855418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70aff5b57e1'
down_revision: Union[str, None] = 'ac9193135831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workspaces_url_name_key', 'workspaces', type_='unique')
    op.drop_column('workspaces', 'url_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('url_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('workspaces_url_name_key', 'workspaces', ['url_name'])
    # ### end Alembic commands ###
